frontend:
  api-url: http://localhost:8000

backend:

  openai:
    model: gpt-4o-mini

  embedding:
    model: all-MiniLM-L6-v2

  vectorstore:
    collection_name: finsight-ai

  database:
    type: postgresql